---
application:
  name: "bot-chill"
  project: "ChillBot"
  organization: "QoveryCommunity"
databases:
- type: mysql
  version: 8.0
  name: database
routers:
- name: "main-bot-chill"
  routes:
  - application_name: "bot-chill"
    paths:
    - "/*"
